import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import logo from "../public/logo.png";
import styles from "./layout.module.css";
import PermanentDrawerLeft from "@/src/components/Sidebar/Sidebar";
import { goToHomePage } from "@/src/utils/utils";

const poppins = Poppins({
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body className={poppins.className}>
        <PermanentDrawerLeft />
        <div className={styles.container}>
          <Image className={styles.logo} height={300} alt="logo" src={logo} />
          {children}
        </div>
      </body>
    </html>
  );
}
